### ISSUE TITLE
Computing Topic List

### ISSUE THREAD

**Issue by fabcooldog** [fabcooldog/resources#1]
These are topics/concepts on the AQA specification, but do not currently have notes in this repository. Note that this does not include **specifically programming-related concepts** as they are covered during the coursework process:
- [x] 3.1.3 - Program flow control (sequencing, selection, iteration)
- [ ] 3.1.8.1 - Computer structure: systems
- [ ] 3.1.8.2 - Computer structure: hardware
- [ ] 3.1.10 - Data representation (needs to be copied from hard copies @stanley-godfrey)
- [x] 3.1.13.2 - Web application concepts
- [ ] 3.1.15.1 - Query methods (SQL)
- [ ] 3.1.16 - The use of computer technology in society

**Comment by fabcooldog** [comment]
Can we convert this into a project? 
@stanley-godfrey

**Comment by stanley-godfrey** [comment]
Done
