### ISSUE TITLE
Name Change Alterations

### ISSUE THREAD

**Issue by fabcooldog** [fabcooldog/resources#20]
As a result of changing the name of the repository to **`resources`**, all the links at the top of the GitHub Pages are broken.

Brownie points for anyone who chips in!

Here is the list of broken pages:

- [x] Computer-Science
  - [x] index.html
  - [x] algorithms.html
  - [x] CPU.html
  - [x] databse-concepts.html
  - [x] SDLC.html
  - [x] memory.html
  - [x] networks.html
- [x] Systems-and-Control/index.html

**Comment by stanley-godfrey** [comment]
Will do

**Comment by stanley-godfrey** [comment]
All done #24
