### ISSUE TITLE
Computer Science Testing

### ISSUE THREAD

**Issue by fabcooldog** [fabcooldog/resources#30]
Can someone add (even if it's brief) a Markdown file for 'testing' as it has been mentioned specifically as important?

Cf. https://bournetocode.com/projects/GCSE_Computing_Fundamentals/pages/3-1-12-Testing.html

**Comment by stanley-godfrey** [comment]
Testing was done a couple of weeks ago: [Testing.md](https://github.com/fabcooldog/resources/blob/master/Computer-Science/Testing.md)

**Comment by fabcooldog** [comment]
Oops!

**Comment by fabcooldog** [comment]
What I meant was the gh-pages version. I'll sort that in a moment, don't worry.

**Comment by stanley-godfrey** [comment]
Could this be done tonight? There is a homework task on it due tomorrow (18/11/16)

**Comment by fabcooldog** [comment]
In progress 👍

**Comment by stanley-godfrey** [comment]
The markdown covers all that is on [http://bournetocode.com](BourneToCode) and has been cross-checked with the spec.

**Comment by fabcooldog** [comment]
I'm going to quickly add some details about trace tables -- what they are and why they're used -- since they often come up in exams.
