### ISSUE TITLE
Online Typo Corrections

### ISSUE THREAD

**Issue by fabcooldog** [fabcooldog/resources#31]
Is it possible to add a text input box onto the site so that anyone can catch spelling errors or even suggest enhancements?

Also, explore whether it is possible to connect this up to GitHub Issues.

**Comment by stanley-godfrey** [comment]
It could be done, perhaps with an HTML form feeding into a PHP/JavaScript back-end sending an email in our direction. Regarding GH Issues, they can only be made through *GitHub* as they are not a *Git* feature.

**Comment by stanley-godfrey** [comment]
Just done some research and, if we want to have this, it would need self-hosting

**Comment by fabcooldog** [comment]
You can use the Github API to interact with GitHub issues.

**Comment by stanley-godfrey** [comment]
Just been doing some research and it's come to my attention that, to create an issue, you need a GitHub account. Thus, would it be better to create a *"bot"* account that we can use to create issues?

**Comment by fabcooldog** [comment]
If you want, go for it. This is as far as I got yesterday, if it helps: https://gist.github.com/fabcooldog/e20280192f7bfe4e8ab19362df413f5c

**Comment by stanley-godfrey** [comment]
Well so far I've had to set up a web server on my Linux box to even do anything (Also, it needs doing in PHP to use the API I believe)

**Comment by stanley-godfrey** [comment]
Well so far I've had to set up a web server on my Linux box to even do anything (Also, it needs doing in PHP to use the API I believe)

**Comment by fabcooldog** [comment]
Why do you need to set up a separate server? I've just used Javascript's `XMLHTTPRequest` object to `get` and `post` data using the API.

**Comment by stanley-godfrey** [comment]
I beg your pardon, I'm doing it with JS now, should be working soon-ish as I've pretty much a copy-and-paste job now

**Comment by fabcooldog** [comment]
What are you copying and pasting?
Could you make a quick Gist so I can see what you're doing?

**Comment by stanley-godfrey** [comment]
I'm just adapting your code to use an HTML form

**Comment by fabcooldog** [comment]
Mine **doesn't work**

**Comment by fabcooldog** [comment]
It `get`s data perfectly but `post` isn't working. I get an error.

**Comment by stanley-godfrey** [comment]
Well I'll get the form accessing done first and then make a Gist... How do I Gist?

**Comment by fabcooldog** [comment]
Big [`Gist`](gist.github.com) button at the top of the page

**Comment by stanley-godfrey** [comment]
Ahh yes... Also, that auth code in your Gist... Am I able to use that or will it go :scream:

**Comment by fabcooldog** [comment]
You can use it perfectly I think. If you're getting an error you could always try generating your own (your profile > developers)

**Comment by stanley-godfrey** [comment]
Okay. Would it be worth, like I mentioned above, making a dedicated issues user which we could use to make the issues, rather than leaving our accounts to do it?

**Comment by fabcooldog** [comment]
For now, new issues is probably best. However, in the future, using HTML, you can make a drop-down list that generates either a comment on an issue entitled `typos`/`page suggestion` etc. or a new issue.

**Comment by stanley-godfrey** [comment]
[Here](https://gist.github.com/stanley-godfrey/0d3b211860995a5daae31882edfd7bdd)

**Comment by fabcooldog** [comment]
That is because of two things:

1. If you want to submit something **to** the site you need to use `post` in your request
2. When you correct (1), you get the following error:

[`HTTP400`](https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-US&k=k(VS.WebClient.Help.HTTP400)) `BAD REQUEST - The request could not be processed by the server due to invalid syntax.`
`(XHR)POST - https://api.github.com/repos/fabcooldog/resources/issues`

**Comment by stanley-godfrey** [comment]
I corrected the GET to POST and, yes, I'm now getting an HTTP 400. I'm now reading the docs and says that all we should need is the issue title and body.

**Comment by stanley-godfrey** [comment]
Do I have pull access?

**Comment by fabcooldog** [comment]
To what?

**Comment by stanley-godfrey** [comment]
The repository

**Comment by fabcooldog** [comment]
No one has pull access, I'm happy to approve any changes you make, though. Also, do remember that you can work in a branch, in which you will have full access

**Comment by stanley-godfrey** [comment]
I've found the problem... You need pull access to create an issue using the API:

> Any user with pull access to a repository can create an issue.

**Comment by fabcooldog** [comment]
Whose key are you using?
If it is either of ours then it is fine -- we can create issues and have pull access; the approvals system just limits pull requests, not issues.

**Comment by fabcooldog** [comment]
Nevertheless, I can disable the approvals for the sake of testing this.

**Comment by stanley-godfrey** [comment]
IT'S FREAKING WORKING!!!!!!!!!

**Comment by fabcooldog** [comment]
With whose key? Try again after I reconnect the approvals.

**Comment by stanley-godfrey** [comment]
My key

**Comment by fabcooldog** [comment]
OK, try now.

**Comment by stanley-godfrey** [comment]
Look in the issue tracker :laughing:

**Comment by fabcooldog** [comment]
Fantastic, could you pop it up on that Gist you made so I can try it at Chez Me

**Comment by stanley-godfrey** [comment]
What's on the menu at *Chez Me* tonight? :laughing:

**Comment by stanley-godfrey** [comment]
[Gist](https://gist.github.com/stanley-godfrey/0d3b211860995a5daae31882edfd7bdd)

**Comment by fabcooldog** [comment]
Javascript and Further Maths 🎈

**Comment by stanley-godfrey** [comment]
So, what now?

**Comment by fabcooldog** [comment]
We need to look at the implementation: instead of copying this into every page, we should put a (relative) link to the ../Javascripts folder in the head.

**Comment by stanley-godfrey** [comment]
Okay. It should be pretty simple to do so. Just chuck a rel link into the head and that should be it. I'll quickly check it though

**Comment by stanley-godfrey** [comment]
[Updated Gist](https://gist.github.com/stanley-godfrey/0d3b211860995a5daae31882edfd7bdd)

**Comment by fabcooldog** [comment]
Furthermore, the input box should have a custom ID that attaches to some CSS that automatically adds the labels to the input boxes to make the site more flexible to update. Finally, we might want to look into the following:

- A spam filter that blocks issues with 25> characters 
- A drop-down list that allows any typos or other common categories to be comments instead of whole new issues
- Anything else?

**Comment by stanley-godfrey** [comment]
What do you mean by the labels?

**Comment by fabcooldog** [comment]
The `First Name:` signs and placeholder text for the boxes.

**Comment by stanley-godfrey** [comment]
Why would they need attaching to the boxes? Next thing I know you'll start adding crates as well

**Comment by fabcooldog** [comment]
I'm not sure how you would do it. Perhaps through divs. Nevertheless, add your current version on to the footer of the main index page - great work!

**Comment by stanley-godfrey** [comment]
Pull request #37
