### ISSUE TITLE
Relative Postitioning

### ISSUE THREAD

**Issue by stanley-godfrey** [fabcooldog/resources#47]
I've just been mucking around with relative positioning (using Dev Tools) on the website and it all seems to be working except for one thing: *the credits don't want to co-operate*. They just split over multiple lines when the window is moved. Therefore, would it be possible to (re)move them?

**Comment by fabcooldog** [comment]
If by credits you mean the `Content based on BourneToCode` then that is based on a CSS class/id.

**Comment by fabcooldog** [comment]
By all means move it if it will not resolve with the rest of the site.
