### ISSUE TITLE
S&C Specification

### ISSUE THREAD

**Issue by fabcooldog** [fabcooldog/resources#5]
### **Materials and Components**
- [x] Done?

- Candidates should develop a working knowledge of a range of materials and control systems appropriate to modelling, prototyping and manufacturing.
- Knowledge and understanding of materials, making processes and components should be of sufficient depth for candidates to make an appropriate and reasoned choice when designing and making a
control system.
- The limited range of materials listed below is intended to define the areas of revision necessary for the
examination, but it is expected that candidates will be able to show a general knowledge of the properties and characteristics of a wider range of materials, including textiles, through their coursework.
- They should also show a general awareness of new
and emerging technologies such as nanotechnology.

### **Materials and Making processes**
- [ ] Done?

- **Materials**
 - Candidates should show a working knowledge of the common woods, manufactured boards, metals and plastics.
- **Manipulating materials**
 - Candidates should cut, shape, form and finish a
variety of materials to specific tolerances.
- **Jigs and fixtures**
 - Candidates should research the use of simple jigs and fixtures to aid manufacture, when consistency in
component size is required.
- **Component Selection**
 
 Candidates should:
  - Select and specify appropriate components from catalogues;
  - Understand values and tolerances.

### **Modelling and Prototyping**
- [x] Done?

Candidates should use construction kits and software to design and test prototype circuits and systems.

**Circuit Construction**

Candidates should:

- Use a variety of temporary and permanent construction techniques, including prototyping board
- Understand the Printed Circuit Board (PCB) design and manufacturing process;
- Build electronic circuits of high quality using PCBs.

- **Assembly**

 - Candidates should use a variety of components and fasteners to build functioning systems.
- **Fault Finding**
 - Candidates should understand how to find faults in systems by using a multi-meter and other test equipment.

### **Control Systems**
- [ ] Done?

**Electronic building blocks**

Candidates should:

- Understand the use of Input, Process and Output building blocks;
- Create simple block diagrams;
- Understand and apply feedback loops.

### **Control Systems – Inputs**
- [ ] Done?

**Sensors**

- Candidates should understand and use Light Dependant Resistor (LDR), thermistor, moisture sensor as input devices to control systems.
**Switches**

- Candidates should understand and use micro-switch, opto-switch, reed switch, tilt switch.
**Potential dividers**

Candidates should:

- Understand and use a potential divider to control input voltage to a circuit to rise or fall in the following conditions: light, dark, hot, cold, wet and dry;
- Understand how to calculate the input voltage using Ohms Law (V = IR);
- Understand how to calculate the Output Voltage of the Potential divider using the formula;![Voltage Divider Diagram](https://github.com/fabcooldog/Odds-and-Sods/AQA%20Voltage%20Divider.JPG)
- Use potential dividers as inputs to microcontrollers
(PICs).

**Analogue and Digital**

- Candidates should use digital and analogue input sensors with PICs and understand the difference between analogue and digital signals.

### **Control Systems – Process**
- [ ] Done?

**Time Delay**

- Candidates should understand and use a time delay in a system by constructing an appropriate circuit and a software Wait command in a program.

**Pulse generation**

- Candidates should understand and use a set frequency.

**Switching**

- Candidates should recognise and select the appropriate switch according to application.

**Logic**

Candidates should:

- Understand and use the following logic gates and construct their truth tables (limited to 2 inputs): AND, OR, NOT;
- Solve logic problems using the above 2 input gates in combination.

**Microcontroller**

- Candidates should select the appropriate microcontroller for the purpose.

**Programmable control**

- Understand that microcontroller ports can be dedicated to input and output states;
- Understand analogue to digital conversion in microcontrollers;
- Construct and run appropriate programs;
- Use a control software package to control the inputs and outputs of a microcontroller.

### **Control Systems – Interface**
- [ ] Done?

**Relays**
Candidates should:

- Understand how a relay can be used as an electrically operated switch to switch and isolate a high current/voltage with a low current/voltage;
- Use relays in a variety of applications, including latching and reversing circuits.

**Drivers**
Candidates should:

- Use Transistors and Relays to switch on outputs which require a higher current than the process component can supply;
- Only NPN and FET will be examined.

### **Control Systems – Output**
- [ ] Done?

**Motion**
Candidates should:

- Identify and use the following types of motion when designing and making:
 - Rotary
 - Oscillating
 - Linear
 - Reciprocating
- Understand methods of converting the following types of motion to the other;
 - Rotary to Linear
 - Linear to Rotary
 - Rotary to Reciprocating
 - Oscillating to Rotary
- Understand how systems can be used to change speed;
- Understand methods of changing the direction or distance of an output;
- Understand their application in industrial situations.

**Optoelectronic**

- Candidates should show an understanding of
common optoelectronic devices including the LED
and lamp.

**Mechanical Systems**

- Candidates should understand how mechanical advantage can be gained using levers and gears.

**Motors and Solenoids**

- Candidates should understand how Motors and Solenoids can be used as outputs.

**Drive systems**
Candidates should:

- Understand methods of transmitting drive from one shaft to another;
 - Gears
 - Belts
 - Chains
 - Drive shafts
- Understand methods of changing the direction or distance of output;
- Take into account slip, noise, friction and maintenance;
- Give examples of how they are used in industry.

**Friction**

- Candidates should understand the application of
friction and explain methods used to reduce friction.

### **Components**
- [ ] Done?

**Resistors and resistance**

Candidates should:

- Understand that resistors control voltage and current in electronic circuits;
- Calculate the value of resistors in series.

**Capacitors**

Candidates should:

- Understand that capacitors store electrical charge;
- Understand polarised and non-polarised capacitors.

**Diode**

Candidates should:

- Understand the characteristics of a silicon diode;
- Understand why it is necessary to use a protective
diode.

### **Component Symbols and Formulae**
- [ ] Done?

**Component Symbols**

Candidates should:

 - Understand the function, use and physical form of the components
   listed below
   - Read and draw diagrams using those symbols
    - 7 segment display
    - 555 timer 
    - IC 
    - Ammeter 
   - AND gate
   - Battery 
   - Bell 
   - Bi-colour light emitting diode
   - Buzzer
   - Capacitor 
   - Cell 
   - Crossing of conductors
   - Double junction
   - Double throw switch
   - Field effect transistor
   - Flashing light emitting diode
   - Fuse
   - Heating Element 
   - Inductor/solenoid
   - Junction of Conductors
   - Lamp
   - Light dependent resistor
   - Light emitting diode
   - Loudspeaker 
   - Microphone
   - Motor 
   - NPN transistor
   - Opto-isolator

**Comment by stanley-godfrey** [comment]
Closing as this has been moved to the Projects tab
