### ISSUE TITLE
Testing System

### ISSUE THREAD

**Issue by fabcooldog** [fabcooldog/resources#51]
Could we try to implement a basic quiz that can be put into the bottom of each page?

The quiz would need to do the following:

- [x] Take in a user input for X number of questions
- [x] Compare the inputs against a list of answers (MULTIPLE ANSWERS NOT YET DONE)
- [x] Give the user a mark out of X and a percentage when they click `mark`

**Comment by stanley-godfrey** [comment]
So using an HTML form with a JavaScript back-end?

**Comment by stanley-godfrey** [comment]
Here's the [gist](https://gist.github.com/stanley-godfrey/de13b63e6ae57de50ea5bf8367f6df60) (no pun intended :laughing:) of what I'm thinking.
